### ISSUE TITLE
[FE] 강의실 페이지 - 강의별 API 연결

### ISSUE THREAD

**Issue by Dahyeonni** [CSID-DGU/2023-2-OSSProj-MSG_UP-8#47]
## IssueName
> 강의실 페이지 - 강의별 API 연결

## Description
> 유저가 선택한 강의실 API 연결 작업

## Todo
- [x] 메인 페이지 컴포넌트 '강의실 바로가기' 연결
- [x] 강의실 페이지 내 강의 TITLE, TIME, PROFESSOR 할당
- [x] 토글 API 연결

## ETC
기타 참고사항
